version: '2.3'

services:
  tensorflow-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    runtime: nvidia
    ports:
      - 8888:8888
    volumes: 
      - $PWD:/tf
    user: ${CURRENT_UID}
    environment:
      - JUPYTER_ENABLE_LAB=yes