version: '2.3'

services:
  tensorflow:
    build:
      context: .
      dockerfile: Dockerfile_cpu
    ports:
      - 80:8888
    volumes: 
      - $PWD:/tf
    user: ${CURRENT_UID}
    environment:
      - JUPYTER_ENABLE_LAB=yes
